In [39]:
import pandas as pd

In [40]:
covid = pd.read_csv('03-27-2020.txt')

In [47]:
covid.Last_Update.max()

'2020-03-27 23:27:48'

In [42]:
covid_us = covid[covid['Country_Region']=='US']

In [43]:
covid_us.Recovered.sum()

869

In [44]:
covid_by_country = covid.groupby('Country_Region')[['Deaths','Recovered', 'Active','Confirmed']].sum()

In [46]:
covid_by_country.sort_values('Confirmed', ascending=False)

                                  Deaths  Recovered  Active  Confirmed
Country_Region
US                                  1581        869       0     101657
Italy                               9134      10950   66414      86498
China                               3296      74720    3881      81897
Spain                               5138       9357   51224      65719
Germany                              342       6658   43871      50871
France                              1997       5707   25698      33402
Iran                                2378      11133   18821      32332
United Kingdom                       761        151   13833      14745
Switzerland                          231       1530   11167      12928
Korea, South                         139       4528    4665       9332
Netherlands                          547          6    8094       8647
Austria                               58        225    7374       7657
Belgium                              289        858    6137       7284
Turkey                                92         42    5564       5698
Canada                                54        256       0       4682
Portugal                              76         43    4149       4268
Norway                                19          6    3730       3755
Brazil                                92          6    3319       3417
Australia                             13        194    2936       3143
Sweden                               105         16    2948       3069
Israel                                12         79    2944       3035
Czechia                                9         11    2259       2279
Denmark                               52         57    2091       2200
Malaysia                              26        259    1876       2161
Ireland                               22          5    2094       2121
Chile                                  5         43    1562       1610
Luxembourg                            15         40    1550       1605
Ecuador                               36          3    1556       1595
Japan                                 49        372    1047       1468
Poland                                16          7    1366       1389
...                                  ...        ...     ...        ...
Mozambique                             0          0       7          7
Benin                                  0          0       6          6
Laos                                   0          0       6          6
Eritrea                                0          0       6          6
Fiji                                   0          0       5          5
Syria                                  0          0       5          5
Guyana                                 1          0       4          5
Zimbabwe                               1          0       4          5
Cabo Verde                             1          0       4          5
Congo (Brazzaville)                    0          0       4          4
Angola                                 0          0       4          4
Holy See                               0          0       4          4
Nepal                                  0          1       3          4
Liberia                                0          0       3          3
Mauritania                             0          0       3          3
Sudan                                  1          0       2          3
Gambia                                 1          0       2          3
Central African Republic               0          0       3          3
Chad                                   0          0       3          3
Bhutan                                 0          0       3          3
Saint Lucia                            0          1       2          3
Somalia                                0          0       3          3
Belize                                 0          0       2          2
Nicaragua                              1          0       1          2
Guinea-Bissau                          0          0       2          2
Saint Kitts and Nevis                  0          0       2          2
Papua New Guinea                       0          0       1          1
Timor-Leste                            0          0       1          1
Libya                                  0          0       1          1
Saint Vincent and the Grenadines       0          0       1          1

[176 rows x 4 columns]